inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - scenario

# Switch off deprecated cop
RSpec/FilePath:
  Enabled: false

# And replace with the preferred cops
RSpec/SpecFilePathFormat:
  Enabled: true

RSpec/SpecFilePathSuffix:
  Enabled: true
